FROM buildpack-deps:bullseye-curl
LABEL maintainer="Echothrust Solutions <info@echothrust.com>"
LABEL description="echoCTF.RED Participants interface (frontend)"
ARG VPNUSER=vpnuser
ARG VPNUSERPASS=vpnuserpass
ARG RED_APP=frontend
ARG MYSQL_HOST=db
ARG MYSQL_USER=vpnuser
ARG MYSQL_PASSWORD=vpnuserpass
ARG MYSQL_DATABASE=echoCTF
ARG GITHUB_OAUTH_TOKEN

ENV DEBIAN_FRONTEND noninteractive
RUN set -ex \
    && apt-get update \
    && apt-get install --no-install-recommends -y git zip unzip tini \
    mariadb-client mcrypt apache2 \
    php php-gd php-mbstring php-mysqli php-dom php-intl php-curl php-memcache php-memcached \
    vim cron

WORKDIR /var/www/echoCTF.RED
COPY ${RED_APP} ./${RED_APP}/
COPY contrib/html-rewrite.conf /etc/apache2/sites-enabled/html-rewrite.conf
ADD https://getcomposer.org/download/latest-stable/composer.phar /usr/local/bin/composer

RUN set -ex \
    && cp ${RED_APP}/config/memcached-local.php ${RED_APP}/config/cache.php \
    && cp ${RED_APP}/config/validationKey-local.php ${RED_APP}/config/validationKey.php \
    && cp ${RED_APP}/config/db-local.php ${RED_APP}/config/db.php \
    && chmod a+x /usr/local/bin/composer \
    && sed -ie "s/127.0.0.1/${MYSQL_HOST}/g" ${RED_APP}/config/cache.php \
    && echo "<?php return [ 'class' => 'yii\db\Connection', 'dsn' => 'mysql:host=${MYSQL_HOST};dbname=${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8mb4',  ];">${RED_APP}/config/db.php \
    && mkdir -p ${RED_APP}/web/assets ${RED_APP}/runtime ${RED_APP}/web/images/avatars/team ${RED_APP}/web/uploads\
    && chown -R www-data ${RED_APP}/web/assets ${RED_APP}/web/images/avatars \
    && chown www-data ${RED_APP}/runtime ${RED_APP}/web/uploads \
    && chmod a+rwx ${RED_APP}/web/uploads \
    && cd ${RED_APP} \
    && cd .. \
    && mv /var/www/html /var/www/html.old \
    && ln -s /var/www/echoCTF.RED/${RED_APP}/web /var/www/html \
    && a2enmod rewrite \
    && rm -rf /root/.composer /usr/src/* /var/lib/apt/lists/*

EXPOSE 80/tcp

VOLUME /var/www/echoCTF.RED/${RED_APP}/web/uploads
WORKDIR /var/www/echoCTF.RED
CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]
ENTRYPOINT ["tini", "--"]
