FROM buildpack-deps:bullseye-curl
LABEL maintainer="Echothrust Solutions <info@echothrust.com>"
LABEL description="echoCTF.RED Administration interface (backend)"
ARG VPNUSER=vpnuser
ARG VPNUSERPASS=vpnuserpass
ARG RED_APP=backend
ARG MYSQL_HOST=db
ARG MYSQL_USER=vpnuser
ARG MYSQL_PASSWORD=vpnuserpass
ARG MYSQL_DATABASE=echoCTF
ARG GITHUB_OAUTH_TOKEN

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /var/www/echoCTF.RED
COPY ${RED_APP} ./${RED_APP}/
ADD https://getcomposer.org/download/latest-stable/composer.phar /usr/local/bin/composer

RUN set -ex \
    && apt-get update \
    && apt-get install --no-install-recommends -y git zip unzip mariadb-client mcrypt apache2 tini \
    php php-gd php-mbstring php-mysqli php-dom php-intl php-curl php-memcache php-memcached \
    vim cron \
    && chmod a+x /usr/local/bin/composer \
    && cp ${RED_APP}/config/cache-local.php ${RED_APP}/config/cache.php \
    && cp ${RED_APP}/config/validationKey-local.php ${RED_APP}/config/validationKey.php \
    && cp ${RED_APP}/config/db-sample.php ${RED_APP}/config/db.php \
    && sed -ie "s/localhost/${MYSQL_HOST}/g" ${RED_APP}/config/db.php \
    && sed -ie "s/127.0.0.1/${MYSQL_HOST}/g" ${RED_APP}/config/cache.php \
    && mkdir -p ${RED_APP}/web/assets ${RED_APP}/runtime \
    && chown www-data ${RED_APP}/web/assets \
    && chown www-data /var/www/echoCTF.RED/${RED_APP}/runtime /var/www/echoCTF.RED/${RED_APP}/web/uploads \
    && chmod a+rwx /var/www/echoCTF.RED/${RED_APP}/web/uploads \
    && cd ${RED_APP} \
    && composer validate \
    && cd .. \
    && mv /var/www/html /var/www/html.old \
    && ln -s /var/www/echoCTF.RED/${RED_APP}/web /var/www/html \
    && a2enmod rewrite \
    && echo "<?php return [ 'class' => 'yii\db\Connection', 'dsn' => 'mysql:host=${MYSQL_HOST};dbname=${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8mb4',  ];">${RED_APP}/config/db.php \
    && apt-get autoremove -y \
    && rm -rf /root/.composer /usr/src/* /var/lib/apt/lists/*

EXPOSE 80/tcp

# Challenge files volume
VOLUME /var/www/echoCTF.RED/${RED_APP}/web/uploads

WORKDIR /var/www/echoCTF.RED
CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]
ENTRYPOINT ["tini", "--"]
