FROM buildpack-deps:bullseye-curl
LABEL maintainer="Echothrust Solutions <info@echothrust.com>"
LABEL description="echoCTF.RED vpn server"
ARG VPNUSER=vpnuser
ARG VPNUSERPASS=vpnuserpass
ARG RED_APP=backend
ARG MYSQL_HOST=db
ARG MYSQL_USER=vpnuser
ARG MYSQL_PASSWORD=vpnuserpass
ARG MYSQL_DATABASE=echoCTF
ARG GITHUB_OAUTH_TOKEN
ENV OPENVPN_ADMIN_PASSWORD OPENVPN_ADMIN_PASSWORD
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /var/www/echoCTF.RED
COPY ${RED_APP} ./${RED_APP}/
COPY contrib ./contrib/
COPY contrib/entrypoint-vpn.sh /entrypoint.sh
ADD https://getcomposer.org/download/latest-stable/composer.phar /usr/local/bin/composer

RUN set -ex \
    && apt-get update \
    && apt-get install --no-install-recommends -y procps git zip unzip mariadb-client tini \
    php php-gd php-mbstring php-mysqli php-dom php-intl php-curl php-memcache php-memcached \
    openvpn netcat-openbsd tcpdump vim.tiny libnet-pcap-perl libpoe-component-pcap-perl cron \
    libdbi-perl libdbd-mysql libdbd-mysql-perl supervisor; \
    cd /var/www/echoCTF.RED/${RED_APP}; \
    chmod a+x /usr/local/bin/composer; \
    touch /sbin/pfctl && chmod +x /sbin/pfctl; \
    ln -s /var/www/echoCTF.RED/${RED_APP}/yii /usr/local/sbin/backend; \
    git config --global url."https://".insteadOf "git://" ; \
    chmod +x /entrypoint.sh; useradd  _openvpn; \
    touch /var/log/openvpn/openvpn.log; \
    rm -rf /root/.composer /usr/src/* /var/lib/apt/lists/*

RUN cd /var/www/echoCTF.RED/${RED_APP} && composer validate
EXPOSE 1194/udp
VOLUME /etc/openvpn
WORKDIR /var/www/echoCTF.RED
CMD ["supervisord -c /var/www/echoCTF.RED/contrib/supervisord.conf"]
ENTRYPOINT ["tini","--", "/entrypoint.sh"]
