FROM buildpack-deps:buster-curl
LABEL maintainer="Echothrust Solutions <info@echothrust.com>"
LABEL description="echoCTF.RED Administration interface (backend)"
ARG VPNUSER=vpnuser
ARG VPNUSERPASS=vpnuserpass
ARG RED_APP=backend
ARG MYSQL_HOST=db
ARG MYSQL_USER=vpnuser
ARG MYSQL_PASSWORD=vpnuserpass
ARG MYSQL_DATABASE=echoCTF
ARG GITHUB_OAUTH_TOKEN

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /var/www/echoCTF.RED
COPY ${RED_APP} ./${RED_APP}/

RUN set -ex; \
    apt-get update; \
    apt-get install --no-install-recommends -y git zip unzip mariadb-client mcrypt apache2 \
    php php-gd php-mbstring php-mysqli php-dom php-intl php-curl php-memcache \
    composer vim; \
    cp ${RED_APP}/config/cache-local.php ${RED_APP}/config/cache.php; \
    cp ${RED_APP}/config/validationKey-local.php ${RED_APP}/config/validationKey.php; \
    cp ${RED_APP}/config/db-sample.php ${RED_APP}/config/db.php; \
    sed -ie "s/localhost/${MYSQL_HOST}/g" ${RED_APP}/config/db.php; \
    sed -ie "s/127.0.0.1/${MYSQL_HOST}/g" ${RED_APP}/config/cache.php; \
    mkdir -p ${RED_APP}/web/assets ${RED_APP}/runtime; \
    chown www-data ${RED_APP}/web/assets; \
    chown www-data ${RED_APP}/runtime; \
    cd ${RED_APP}; \
    [ -z "${GITHUB_OAUTH_TOKEN}" ] || git config --global url."https://".insteadOf "git://" ; \
    [ -z "${GITHUB_OAUTH_TOKEN}" ] || composer config -g github-oauth.github.com "${GITHUB_OAUTH_TOKEN}"; \
    [ -z "${GITHUB_OAUTH_TOKEN}" ] || composer config --global github-protocols https; \
    [ -z "${GITHUB_OAUTH_TOKEN}" ] || composer install --no-dev --prefer-dist --no-progress --no-suggest ; \
    [ -z "${GITHUB_OAUTH_TOKEN}" ] || composer clearcache; \
    cd ..; \
    mv /var/www/html /var/www/html.old; \
    ln -s /var/www/echoCTF.RED/${RED_APP}/web /var/www/html; \
    a2enmod rewrite; \
    echo "<?php return [ 'class' => 'yii\db\Connection', 'dsn' => 'mysql:host=${MYSQL_HOST};dbname=${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8',  ];">${RED_APP}/config/db.php; \
    apt-get autoremove -y; \
    rm -rf /root/.composer /usr/src/* /var/lib/apt/lists/*

EXPOSE 80/tcp

# Challenge files volume
VOLUME /var/www/echoCTF.RED/${RED_APP}/web/uploads

WORKDIR /var/www/echoCTF.RED
CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]
