FROM buildpack-deps:buster-curl
LABEL maintainer="Echothrust Solutions <info@echothrust.com>"
LABEL description="echoCTF.RED vpn server"
ARG VPNUSER=vpnuser
ARG VPNUSERPASS=vpnuserpass
ARG RED_APP=backend
ARG MYSQL_HOST=db
ARG MYSQL_USER=vpnuser
ARG MYSQL_PASSWORD=vpnuserpass
ARG MYSQL_DATABASE=echoCTF

ENV DEBIAN_FRONTEND noninteractive
WORKDIR /var/www/echoCTF.RED
COPY ${RED_APP} ./${RED_APP}/
COPY contrib ./contrib/
COPY contrib/entrypoint-vpn.sh /entrypoint.sh


RUN set -ex \
    && apt-get update \
    && apt-get install --no-install-recommends -y procps git zip unzip mariadb-client \
    php php-gd php-mbstring php-mysqli php-dom php-intl php-curl php-memcache \
    composer openvpn netcat-openbsd; \
    cd /var/www/echoCTF.RED/${RED_APP}; \
    git config --global url."https://".insteadOf "git://" ; \
    composer config --global github-protocols https; \
    composer install --no-dev; \
    composer clearcache; \
    rm -rf /usr/src/* /var/lib/apt/lists/*; \
    chmod +x /entrypoint.sh; useradd  _openvpn; \
    touch /var/log/openvpn/openvpn.log


EXPOSE 1194/udp
VOLUME /etc/openvpn
WORKDIR /var/www/echoCTF.RED

CMD ["tail -f /var/log/openvpn/openvpn.log"]
ENTRYPOINT ["/entrypoint.sh"]
