version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install mkdocs mkdocs-material
    - mkdocs build -f .mkdocs.yml
mkdocs:
  configuration: .mkdocs.yml
formats: all
