pass in quick on interconnect inet proto {tcp,udp} from <service_clients> to port { 11200, 11201, 11211, 11254, 3306 }
pass in quick on interconnect inet proto icmp from <service_clients>
pass quick from <administrators> label "administrators"