<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\settings\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form=ActiveForm::begin();?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true])->hint('The username...') ?>

    <?= $form->field($model, 'auth_key')->textInput(['maxlength' => true])->hint('A key automatically generated by the application') ?>

    <?= $form->field($model, 'new_password')->textInput(['maxlength' => true])->hint('This is not the password, but the password hash. You may only change this if you figure out how!') ?>

    <?= $form->field($model, 'password_reset_token')->textInput(['maxlength' => true])->hint('An automatically generated by the application token, used for sending password reset links to the user') ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true])->hint('The user email address') ?>

    <?= $form->field($model, 'status')->dropDownList([0 => 'Deleted', 9 => 'Inactive', 10 => 'Active', ], ['prompt' => 'Choose user status'])->hint('Set the player status. TODO') ?>

    <?= $form->field($model, 'verification_token')->textInput(['maxlength' => true])->hint('An automatically generated by the application token, used for verifing user email') ?>

    <?= $form->field($model, 'admin')->checkbox()->hint('Check if the user is an administrtor. Uncheck if the user is a moderator') ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end();?>

</div>
