<?php

namespace app\modules\moderation\models;

use Yii;
use app\modules\frontend\models\Player;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "abuser".
 *
 * @property int $id
 * @property int $player_id
 * @property string|null $title
 * @property string|null $body
 * @property string|null $reason
 * @property string $model
 * @property int $model_id
 * @property string|null $created_at
 * @property string|null $updated_at
 *
 * @property Player $player
 */
class Abuser extends \yii\db\ActiveRecord
{
  public $created_at_ago, $updated_at_ago;
  public function behaviors()
  {
    return [
      [
        'class' => TimestampBehavior::class,
        'value' => new \yii\db\Expression('NOW()'),

      ]
    ];
  }


  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'abuser';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
      [['title', 'body', 'reason', 'created_at', 'updated_at'], 'default', 'value' => null],
      [['player_id', 'model', 'model_id'], 'required'],
      [['player_id', 'model_id'], 'integer'],
      [['body'], 'string'],
      [['created_at', 'updated_at'], 'safe'],
      [['title', 'reason', 'model'], 'string', 'max' => 255],
      [['player_id'], 'exist', 'skipOnError' => true, 'targetClass' => Player::class, 'targetAttribute' => ['player_id' => 'id']],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'player_id' => 'Player ID',
      'title' => 'Title',
      'body' => 'Body',
      'reason' => 'Reason',
      'model' => 'Model',
      'model_id' => 'Model ID',
      'created_at' => 'Created At',
      'updated_at' => 'Updated At',
    ];
  }

  /**
   * Gets query for [[Player]].
   *
   * @return \yii\db\ActiveQuery|yii\db\ActiveQuery
   */
  public function getPlayer()
  {
    return $this->hasOne(Player::class, ['id' => 'player_id']);
  }

  /**
   * Get related record for the current record
   */
  public function getRelated()
  {
    switch ($this->model) {
      case 'treasure':
        return $this->hasOne(\app\modules\gameplay\models\Treasure::class, ['id' => 'model_id']);
      default:
        break;
    }
    return null;
  }

  /**
   * Get formatted record
   */
  public function getFormatted()
  {
    if ($this->related === null) {
      return sprintf('produced %s generated by [%s] for model [%s] with id [%d], <abbr title="%s">%s</abbr>', $this->title, $this->reason, $this->model, $this->model_id, $this->created_at, $this->created_at_ago);
    }

    switch ($this->reason) {
      case 'tai_player_treasure':
        return sprintf('claimed the flag [%s] for [%s] before findings, <abbr title="%s">%s</abbr>', $this->related->name, $this->related->target->name, $this->created_at, $this->created_at_ago);
    }
  }

  /**
   * {@inheritdoc}
   * @return AbuserQuery the active query used by this AR class.
   */
  public static function find()
  {
    return new AbuserQuery(get_called_class());
  }

  /**
   * Try to return the reason for this failed claim
   */
  public function forFailedClaim()
  {
    if (preg_match('/(?:etsctf|tsctf|sctf|ctf|tf|f)_([a-z0-9]+)/i', $this->title, $matches)) {
      $claimedHash = $matches[0];
      $string = $matches[1];
    } else {
      $claimedHash = $string = null;
    }
    if ($string != null) {
      $secretKey = \Yii::$app->sys->treasure_secret_key;
      $result = \app\modules\gameplay\models\TreasureFinder::findByEncryptedCode($secretKey, '%' . $string . '%');
      if (is_array($result) && $result !== []) {
        if (array_key_exists('player_id', $result)) {
          $originalPlayer = \app\modules\frontend\models\Player::findOne($result['player_id']);
        }

        if (array_key_exists('treasure_id', $result)) {
          $originalTreasure = \app\modules\gameplay\models\Treasure::findOne($result['treasure_id']);
        }

        // check if its just a typo for the same user so they havent copied a flag
        if (array_key_exists('player_id', $result) && intval($result['player_id']) == intval($this->player_id)) {
          return 'False alarm this is their own code';
        }

        $profileLink = \app\widgets\ProfileLink::widget([
          'username' => $originalPlayer->username,
          'actions' => false
        ]);
        $offenderLink = \app\widgets\ProfileLink::widget([
          'username' => $this->player->username,
          'actions' => false
        ]);
        if ($this->player->teamPlayer)
          $from = sprintf("[%s] from team [%s]", $offenderLink, $this->player->teamPlayer->team->name);
        else
          $from = "[$offenderLink]";

        if ($originalPlayer->teamPlayer)
          $to = sprintf("[%s] from team [%s]", $profileLink, $originalPlayer->teamPlayer->team->name);
        else
          $to = "[$profileLink]";
        $msg = "- $from tried to claim code [<small><code>" . trim($claimedHash) . "</code></small>] that belongs to player $to for target [" . $originalTreasure->target->name . "] and treasure [" . $originalTreasure->name . "]";
        return $msg;
      }
    }

    return null;
  }
  /**
   * Check if the claimed hash is a near-typo of the player's own actual flag.
   * Returns a "false alarm" message if it looks like a typo, null otherwise.
   */
  private function checkForTypo(string $claimedHash, $actualHash): ?string
  {
    $actual  = trim($actualHash); // adjust to however you retrieve the player's actual flag
    $claimed = trim($claimedHash);

    if ($actual === '') {
      return null;
    }

    $distance = levenshtein(strtolower($claimed), strtolower($actual));

    if ($distance === 0 || $distance > 2) {
      return null;
    }

    $offenderLink = \app\widgets\ProfileLink::widget([
      'username' => $this->player->username,
      'actions'  => false
    ]);

    $diff = $this->buildInlineDiff($claimed, $actual);

    return "False alarm, [$offenderLink] had a typo in their claim: $diff";
  }

  /**
   * Build a character-level inline diff between two strings.
   * Mismatched characters are highlighted: red for claimed, green for actual.
   */
  private function buildInlineDiff(string $claimed, string $actual): string
  {
    $maxLen     = max(strlen($claimed), strlen($actual));
    $claimedOut = '';
    $actualOut  = '';

    for ($i = 0; $i < $maxLen; $i++) {
      $c = $claimed[$i] ?? '';
      $a = $actual[$i]  ?? '';

      if ($c === $a) {
        $claimedOut .= htmlspecialchars($c);
        $actualOut  .= htmlspecialchars($a);
      } else {
        if ($c !== '') $claimedOut .= '<span style="background:#ffcccc;color:#900;font-weight:bold">' . htmlspecialchars($c) . '</span>';
        if ($a !== '') $actualOut  .= '<span style="background:#ccffcc;color:#060;font-weight:bold">' . htmlspecialchars($a) . '</span>';
      }
    }

    return "<code>$claimedOut</code> vs <code>$actualOut</code>";
  }
}
