[program:easeprobe]
command=/usr/local/bin/easeprobe -f /etc/easeprobe/config.yaml
user=root
autostart=true
autorestart=true
stopsignal=TERM
stdout_logfile=/var/log/easeprobe-supervisor.log
redirect_stderr=true

[program:nfcapd]
command=/usr/local/bin/nfcapd -4 -p 9995 -t 300 -M /var/nfcapd/exp
#command=/usr/local/bin/nfcapd -b 10.7.0.123 -b 10.0.0.123 -p 9995 -t 300 -M /var/nfcapd/exp
#command=/usr/local/bin/nfcapd -b 10.7.0.123 -p 9995 -t 300 -M /var/nfcapd/exp
user=_nfcapd
autostart=true
autorestart=true
stopsignal=TERM
stdout_logfile=/var/log/nfcapd-supervisor.log
redirect_stderr=true

[program:memcached_exporter]
command=/usr/local/bin/memcached_exporter --memcached.address=10.7.0.253:11211 --web.listen-address=127.0.0.1:9150
user=_memcachedexp
autostart=true
autorestart=true
stdout_logfile=/var/log/memcached_exporter-supervisor.log
redirect_stderr=true

[program:mysqld_exporter]
command=/usr/local/bin/mysqld_exporter --config.my-cnf=/etc/mysqld_exporter/my.cnf --no-collect.slave_status --mysqld.address=10.7.0.253:3306 --web.listen-address=127.0.0.1:9104
user=_mysqldexp
autostart=true
autorestart=true
stdout_logfile=/var/log/mysqld_exporter-supervisor.log
redirect_stderr=true
