{
 "title": "Platform hosts",
 "tags": [ "echoctf" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(ifHCInOctets, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU busy per server, last minute average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU $server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (hrProcessorLoad{instance=~\"$server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Memory used per server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory $server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * hrStorageUsed{instance=~\"$server\",hrStorageDescr=\"Physical memory\"} / hrStorageSize{instance=~\"$server\",hrStorageDescr=\"Physical memory\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Filesystems per server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Filesystems $server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * hrStorageUsed{instance=~\"$server\",hrStorageDescr=~\"/.*\"} / hrStorageSize{instance=~\"$server\",hrStorageDescr=~\"/.*\"}",
     "legendFormat": "{{hrStorageDescr}}"
    }
   ]
  }
 ]
}