<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\modules\frontend\models\Player;

/* @var $this yii\web\View */
/* @var $model app\modules\frontend\models\Team */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="team-form">

    <?php $form=ActiveForm::begin();?>
    <div class="row">
      <div class="col-md-4"><?= $form->field($model, 'name')->textInput(['maxlength' => true])->hint('The name of the team (will be shown on scoreboards, streams and other public locations)') ?></div>
      <div class="col-md-4"><?= $form->field($model, 'owner_id')->dropDownList(ArrayHelper::map(Player::find()->orderBy(['username'=>SORT_ASC])->all(), 'id', 'username'), ['prompt'=>'Select the owner for team'])->Label('Owner')->hint('Choose the player who will be the owner of the team')?></div>
      <div class="col-md-4"><?= $form->field($model, 'token')->textInput(['maxlength' => true])->hint('A token to be given to other players so they may join the team (automatically generated by the applicaion)') ?></div>
    </div>
    <div class="row">
      <div class="col-md-6"><?= $form->field($model, 'academic')->checkbox()->hint('Whether the team is academic or not') ?></div>
      <div class="col-md-6"><?= $form->field($model, 'inviteonly')->checkbox()->hint('Whether the team is inviteonly on listings') ?></div>
    </div>
    <div class="row">
      <div class="col-md-6"><?= $form->field($model, 'recruitment')->textArea()->hint('Recruitment text for new members') ?></div>
      <div class="col-md-6"><?= $form->field($model, 'description')->textArea()->hint('A description of the team') ?></div>
    </div>

    <div class="form-group text-center">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end();?>

</div>
