myname: "conductor.mydomain"
ansible_host: "1.2.3.4"
backups:
  - { tgz: "/tmp/altroot.tgz", src: '/altroot' }
  - { tgz: "/altroot/root.tgz", src: '/root' }
  - { tgz: "/altroot/etc.tgz", src: '/etc'  }
  - { tgz: "/altroot/varcron.tgz", src: '/var/cron'  }
  - { tgz: "/altroot/varlog.tgz", src: '/var/log'  }
  - { tgz: "/altroot/home.tgz", src: '/home'  }

pre_backups:
APP_DIR: "/root/sources"
REPO: "/root/sources"

targets_interface: vio1
interconnect_interface: "vio2"
targets_if_ipv4: 10.0.0.123
interconnect_interface_ip: 10.7.0.123
targets_netmask: 255.255.0.0
grafana_user: admin
grafan_password: grafana