hostname: db.mydomain
backups:
  - { tgz: "/tmp/altroot.tgz", src: '/altroot' }
  - { tgz: "/altroot/root.tgz", src: '/root' }
  - { tgz: "/altroot/etc.tgz", src: '/etc'  }
  - { tgz: "/altroot/varcron.tgz", src: '/var/cron'  }
  - { tgz: "/altroot/varmysql.tgz", src: '/var/mysql'  }
  - { tgz: "/altroot/home.tgz", src: '/home'  }

pre_backups:
  - "/usr/local/bin/mysqldump -YKER --add-drop-table --hex-blob --triggers --tz-utc echoCTF | gzip -9 > /altroot/echoCTF-full-$(date +%Y%m%d).sql.gz"
  - "mysql -e 'PURGE BINARY LOGS BEFORE NOW()'"

REPO: /root/sources

interconnect_interface_ip: "{{db_ip}}"
#key_buffer_size: "512k"
#innodb_buffer_pool_size: "2G"
#innodb_log_file_size: "512M"
#max_connections: "500"
#thread_handling: "pool-of-threads"
#thread_pool_size: "4"
